/*! 
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	 
 */
(function(){sap.ui.define(["./errors"],function(t){function e(t,e){for(var n=0;n<e.length;n++){var r=e[n];r.enumerable=r.enumerable||false;r.configurable=true;if("value"in r)r.writable=true;Object.defineProperty(t,r.key,r)}}function n(t,n,r){if(n)e(t.prototype,n);if(r)e(t,r);Object.defineProperty(t,"prototype",{writable:false});return t}function r(t,e){if(!(t instanceof e)){throw new TypeError("Cannot call a class as a function")}}function i(t,e){if(typeof e!=="function"&&e!==null){throw new TypeError("Super expression must either be null or a function")}t.prototype=Object.create(e&&e.prototype,{constructor:{value:t,writable:true,configurable:true}});Object.defineProperty(t,"prototype",{writable:false});if(e)o(t,e)}function o(t,e){o=Object.setPrototypeOf?Object.setPrototypeOf.bind():function t(e,n){e.__proto__=n;return e};return o(t,e)}function a(t){var e=s();return function n(){var r=u(t),i;if(e){var o=u(this).constructor;i=Reflect.construct(r,arguments,o)}else{i=r.apply(this,arguments)}return l(this,i)}}function l(t,e){if(e&&(typeof e==="object"||typeof e==="function")){return e}else if(e!==void 0){throw new TypeError("Derived constructors may only return object or undefined")}return c(t)}function c(t){if(t===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return t}function s(){if(typeof Reflect==="undefined"||!Reflect.construct)return false;if(Reflect.construct.sham)return false;if(typeof Proxy==="function")return true;try{Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}));return true}catch(t){return false}}function u(t){u=Object.setPrototypeOf?Object.getPrototypeOf.bind():function t(e){return e.__proto__||Object.getPrototypeOf(e)};return u(t)}
/*!
   * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	
   */var f=t["ESHClientError"];var h=function(t){i(o,t);var e=a(o);function o(t){var n;var i;r(this,o);t.message=(n=t.message)!==null&&n!==void 0?n:"Duplicate node";i=e.call(this,{message:t.message,name:"DuplicateException"});i.node=t.node;return i}return n(o)}(f);var p=function(){function t(e,n,i){r(this,t);this.parent=e;this.nodeId=n;this.labelCalculator=i;this.childMap={};this.children=[]}n(t,[{key:"insert",value:function e(n,r){if(n.length===0){this.data=this.labelCalculator.options.data(r);this.obj=r;this.calculateLabel();return}var i=n[0];var o=this.childMap[i];if(n.length===1&&o){throw new h({node:o})}if(!o){o=new t(this,i,this.labelCalculator);this.childMap[i]=o;this.children.push(o);if(this.children.length===2){this.children[0].recalculateLabels()}}o.insert(n.slice(1),r)}},{key:"recalculateLabels",value:function t(){var e=[];this.collectLeafs(e);for(var n=0;n<e.length;++n){e[n].calculateLabel()}}},{key:"collectLeafs",value:function t(e){if(this.isLeaf()){e.push(this);return}for(var n=0;n<this.children.length;++n){this.children[n].collectLeafs(e)}}},{key:"isLeaf",value:function t(){return this.children.length===0}},{key:"hasSibling",value:function t(){return this.parent&&this.parent.children.length>=2}},{key:"isChildOfRoot",value:function t(){return this.parent&&this.parent.nodeId==="__ROOT"}},{key:"collectPath",value:function t(e,n){if(!this.parent){return}if(n||this.hasSibling()||this.isChildOfRoot()){e.push(this.nodeId);n=true}if(this.parent){this.parent.collectPath(e,n)}}},{key:"calculateLabel",value:function t(){var e=[];this.collectPath(e);e.reverse();this.labelCalculator.options.setLabel(this.obj,e,this.data)}}]);return t}();var d=function(){function t(e){r(this,t);this.options=e;this.rootNode=new p(null,"__ROOT",this)}n(t,[{key:"calculateLabel",value:function t(e){var n=this.options.key(e);try{this.rootNode.insert(n,e)}catch(t){if(t.name==="DuplicateException"){this.options.setFallbackLabel(t.node.obj,t.node.data);this.options.setFallbackLabel(e,this.options.data(e));return}throw t}}}]);return t}();var b={__esModule:true};b.LabelCalculator=d;return b})})();