/*! 
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	 
 */
(function(){sap.ui.define(["./ResultSetItem","../core/core"],function(t,e){function r(t,e){var r=typeof Symbol!=="undefined"&&t[Symbol.iterator]||t["@@iterator"];if(!r){if(Array.isArray(t)||(r=n(t))||e&&t&&typeof t.length==="number"){if(r)t=r;var i=0;var o=function(){};return{s:o,n:function(){if(i>=t.length)return{done:true};return{done:false,value:t[i++]}},e:function(t){throw t},f:o}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}var u=true,a=false,l;return{s:function(){r=r.call(t)},n:function(){var t=r.next();u=t.done;return t},e:function(t){a=true;l=t},f:function(){try{if(!u&&r.return!=null)r.return()}finally{if(a)throw l}}}}function n(t,e){if(!t)return;if(typeof t==="string")return i(t,e);var r=Object.prototype.toString.call(t).slice(8,-1);if(r==="Object"&&t.constructor)r=t.constructor.name;if(r==="Map"||r==="Set")return Array.from(t);if(r==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(r))return i(t,e)}function i(t,e){if(e==null||e>t.length)e=t.length;for(var r=0,n=new Array(e);r<e;r++)n[r]=t[r];return n}function o(t,e){if(!(t instanceof e)){throw new TypeError("Cannot call a class as a function")}}function u(t,e){for(var r=0;r<e.length;r++){var n=e[r];n.enumerable=n.enumerable||false;n.configurable=true;if("value"in n)n.writable=true;Object.defineProperty(t,n.key,n)}}function a(t,e,r){if(e)u(t.prototype,e);if(r)u(t,r);Object.defineProperty(t,"prototype",{writable:false});return t}function l(t,e){if(typeof e!=="function"&&e!==null){throw new TypeError("Super expression must either be null or a function")}t.prototype=Object.create(e&&e.prototype,{constructor:{value:t,writable:true,configurable:true}});Object.defineProperty(t,"prototype",{writable:false});if(e)f(t,e)}function f(t,e){f=Object.setPrototypeOf?Object.setPrototypeOf.bind():function t(e,r){e.__proto__=r;return e};return f(t,e)}function c(t){var e=v();return function r(){var n=p(t),i;if(e){var o=p(this).constructor;i=Reflect.construct(n,arguments,o)}else{i=n.apply(this,arguments)}return s(this,i)}}function s(t,e){if(e&&(typeof e==="object"||typeof e==="function")){return e}else if(e!==void 0){throw new TypeError("Derived constructors may only return object or undefined")}return b(t)}function b(t){if(t===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return t}function v(){if(typeof Reflect==="undefined"||!Reflect.construct)return false;if(Reflect.construct.sham)return false;if(typeof Proxy==="function")return true;try{Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}));return true}catch(t){return false}}function p(t){p=Object.setPrototypeOf?Object.getPrototypeOf.bind():function t(e){return e.__proto__||Object.getPrototypeOf(e)};return p(t)}function y(t,e,r){if(e in t){Object.defineProperty(t,e,{value:r,enumerable:true,configurable:true,writable:true})}else{t[e]=r}return t}
/*!
   * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	
   */var d=t["ResultSetItem"];var h=e["generateGuid"];var g=function(t){l(n,t);var e=c(n);function n(t){var r,i,u,a,l,f,c,s;var v;o(this,n);v=e.call(this,t);y(b(v),"score",0);v.dataSource=(r=t.dataSource)!==null&&r!==void 0?r:v.dataSource;v.attributes=t.attributes;v.attributesMap={};if(Array.isArray(v.attributes)&&v.attributes.length>0){for(var p=0;p<v.attributes.length;++p){var d=v.attributes[p];v.attributesMap[d.id]=d}}v.titleAttributes=(i=t.titleAttributes)!==null&&i!==void 0?i:v.titleAttributes;v.titleDescriptionAttributes=(u=t.titleDescriptionAttributes)!==null&&u!==void 0?u:v.titleDescriptionAttributes;v.detailAttributes=(a=t.detailAttributes)!==null&&a!==void 0?a:v.detailAttributes;v.defaultNavigationTarget=(l=t.defaultNavigationTarget)!==null&&l!==void 0?l:v.defaultNavigationTarget;v.navigationTargets=(f=t.navigationTargets)!==null&&f!==void 0?f:v.navigationTargets;v.score=(c=t.score)!==null&&c!==void 0?c:v.score;v.hierarchyNodePaths=(s=t.hierarchyNodePaths)!==null&&s!==void 0?s:v.hierarchyNodePaths;return v}a(n,[{key:"key",get:function t(){var e=[];e.push(this.dataSource.id);var n=r(this.titleAttributes),i;try{for(n.s();!(i=n.n()).done;){var o=i.value;var u=o.getSubAttributes();var a=r(u),l;try{for(a.s();!(l=a.n()).done;){var f=l.value;e.push(f.value)}}catch(t){a.e(t)}finally{a.f()}}}catch(t){n.e(t)}finally{n.f()}if(e.length===1){e.push(h())}return e.join("-")}},{key:"toString",value:function t(){var e;var r=[];var n=[];for(e=0;e<this.titleAttributes.length;++e){var i=this.titleAttributes[e];n.push(i.toString())}r.push("--"+n.join(" "));for(e=0;e<this.detailAttributes.length;++e){var o=this.detailAttributes[e];r.push(o.toString())}return r.join("\n")}}]);return n}(d);var A={__esModule:true};A.SearchResultSetItem=g;return A})})();